'use client'
/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/P2CVam3RFtw
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Chivo } from 'next/font/google'
import { Rubik } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "../ui/label"
import { Input } from "../ui/input"
import { Textarea } from "../ui/textarea"
import { Button } from "../ui/button"
import { MailIcon } from "lucide-react"
import { BotIcon } from "lucide-react"
import Link from "next/link"

export function HelpCenter() {
  return (
    <div className="w-[100%] lg:w-[900px] m-auto" >
      <main className="flex-1 px-4 py-8 sm:px-6 md:px-8 mt-[100px] bg-[#020712]">
        <div className="mx-auto max-w-4xl space-y-8">
          <div>
            <h1 className="text-3xl font-bold">Help Center</h1>
            <p className="text-gray-400">Get the support you need to make the most of Hanzo.</p>
          </div>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 bg-[#000]">
            <div className="rounded-lg bg-black p-6 text-gray-300 md:col-span-2">
              <h2 className="text-xl font-bold">Create Support Ticket</h2>
              <p className="text-gray-400">Fill out the form below to create a support ticket.</p>
              <form className="mt-4 space-y-4">
                <div>
                  <Label htmlFor="name" className="font-inter">
                    Name
                  </Label>
                  <Input
                    id="name"
                    placeholder="Your name"
                    className="font-inter bg-black border border-gray-600 text-gray-400"
                  />
                </div>
                <div>
                  <Label htmlFor="email" className="font-inter">
                    Email
                  </Label>
                  <Input
                    id="email"
                    type="email"
                    placeholder="Your email"
                    className="font-inter bg-black border border-gray-600 text-gray-400"
                  />
                </div>
                <div>
                  <Label htmlFor="message" className="font-inter">
                    Message
                  </Label>
                  <Textarea
                    id="message"
                    placeholder="Describe your issue"
                    className="min-h-[120px] font-inter bg-black border border-gray-600 text-gray-400"
                  />
                </div>
                <Button type="submit" className="w-full font-inter bg-white text-black">
                  Submit Ticket
                </Button>
              </form>
            </div>
            <div className="rounded-lg bg-black p-6 text-gray-300">
              <div className="flex items-center">
                <h2 className="text-xl font-bold">Email Us</h2>
                <MailIcon className="h-5 w-5 ml-2 stroke-current" />
              </div>
              <p className="text-gray-400">
                If you would like to talk to a real person that wants to help you email us at{" "}
                <Link href="#" className="text-gray-400 hover:underline" prefetch={false}>
                  hi@hanzo.ai
                </Link>
              </p>
              <div className="mt-4">
                <Button
                  variant="outline"
                  onClick={() => {
                    window.location.href = "mailto:hi@hanzo.ai?subject=Help Request&body=Dear Hanzo Team,"
                  }}
                  className="w-full font-inter bg-white text-black"
                >
                  Open Email Client
                </Button>
              </div>
            </div>
            <div className="rounded-lg bg-black p-6 text-gray-300">
              <div className="flex items-center">
                <h2 className="text-xl font-bold">Ask AI</h2>
                <BotIcon className="h-5 w-5 ml-2 stroke-current" />
              </div>
              <p className="text-gray-400">Get instant answers to your questions from our AI assistant.</p>
              <div className="mt-4">
                <Button variant="outline" onClick={() => {}} className="w-full font-inter bg-white text-black">
                  Ask AI
                </Button>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}


