/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/5v21v3WJ02d
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Chivo } from 'next/font/google'
import { Rubik } from 'next/font/google'

chivo({
  subsets: ['latin'],
  display: 'swap',
})

rubik({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function AllBlog() {
  return (
    <div className="flex pt-20 min-h-screen flex-col bg-gray-950 text-gray-50">
      <main className="flex-1 px-4 py-8 sm:px-6 md:px-8">
        <div className="mx-auto max-w-4xl space-y-8">
          <div className="grid gap-6 max-w-6xl w-full mx-auto">
            <div>
              <h1 className="text-3xl font-bold">All Blog Posts</h1>
              <p className="text-gray-400">
                Explore our collection of insightful articles and stay ahead of the curve.
              </p>
            </div>
            <div className="grid gap-6 lg:grid-cols-3">
              <div className="relative group">
                <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                  <span className="sr-only">View</span>
                </Link>
                <img
                  src="/placeholder.svg"
                  alt="Cover image"
                  width={200}
                  height={200}
                  className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
                />
                <div className="flex-1 py-4">
                  <h3 className="font-semibold tracking-tight">
                    Revolutionizing AI: Hanzo's Cutting-Edge Advancements
                  </h3>
                  <small className="text-sm leading-none text-gray-400">Posted on June 1, 2023</small>
                </div>
              </div>
              <div className="relative group">
                <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                  <span className="sr-only">View</span>
                </Link>
                <img
                  src="/placeholder.svg"
                  alt="Cover image"
                  width={200}
                  height={200}
                  className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
                />
                <div className="flex-1 py-4">
                  <h3 className="font-semibold tracking-tight">
                    The Future of Quantum Computing: Unlocking Limitless Possibilities
                  </h3>
                  <small className="text-sm leading-none text-gray-400">Posted on May 15, 2023</small>
                </div>
              </div>
              <div className="relative group">
                <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                  <span className="sr-only">View</span>
                </Link>
                <img
                  src="/placeholder.svg"
                  alt="Cover image"
                  width={200}
                  height={200}
                  className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
                />
                <div className="flex-1 py-4">
                  <h3 className="font-semibold tracking-tight">
                    Cybersecurity in the Digital Age: Protecting Your Data, Safeguarding Your Future
                  </h3>
                  <small className="text-sm leading-none text-gray-400">Posted on April 28, 2023</small>
                </div>
              </div>
              <div className="relative group">
                <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                  <span className="sr-only">View</span>
                </Link>
                <img
                  src="/placeholder.svg"
                  alt="Cover image"
                  width={200}
                  height={200}
                  className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
                />
                <div className="flex-1 py-4">
                  <h3 className="font-semibold tracking-tight">
                    The Rise of Sustainable Technology: Innovations for a Greener Future
                  </h3>
                  <small className="text-sm leading-none text-gray-400">Posted on April 10, 2023</small>
                </div>
              </div>
              <div className="relative group">
                <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                  <span className="sr-only">View</span>
                </Link>
                <img
                  src="/placeholder.svg"
                  alt="Cover image"
                  width={200}
                  height={200}
                  className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
                />
                <div className="flex-1 py-4">
                  <h3 className="font-semibold tracking-tight">
                    The Future of Transportation: Autonomous Vehicles and Beyond
                  </h3>
                  <small className="text-sm leading-none text-gray-400">Posted on March 25, 2023</small>
                </div>
              </div>
              <div className="relative group">
                <Link href="#" className="absolute inset-0 z-10" prefetch={false}>
                  <span className="sr-only">View</span>
                </Link>
                <img
                  src="/placeholder.svg"
                  alt="Cover image"
                  width={200}
                  height={200}
                  className="rounded-lg object-cover w-full aspect-square group-hover:opacity-50 transition-opacity"
                />
                <div className="flex-1 py-4">
                  <h3 className="font-semibold tracking-tight">
                    The Power of Blockchain: Revolutionizing Industries and Transforming Trust
                  </h3>
                  <small className="text-sm leading-none text-gray-400">Posted on March 8, 2023</small>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
