/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/HugN0K8ixFp
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Work_Sans } from 'next/font/google'
import { Chivo } from 'next/font/google'

work_sans({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"

export function ErrorPage() {
  return (
    <div className="flex min-h-[100dvh] flex-col items-center justify-center bg-black text-[white] font-inter">
      <div className="mx-auto max-w-md text-center">
        <h1 className="text-8xl font-bold text-[white]">404</h1>
        <p className="mt-4 text-2xl text-[white]">Oops, page not found</p>
        <Link
          href="#"
          className="mt-6 inline-flex items-center rounded-[5px] bg-[white] px-4 py-2 text-sm font-medium text-[black] shadow-sm transition-colors hover:bg-gray-200 focus:outline-none focus:ring-2 focus:ring-white focus:ring-offset-2"
          prefetch={false}
        >
          Go to Homepage
        </Link>
      </div>
    </div>
  )
}
